name: build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: |
          go get -u golang.org/x/sys
          make buildall
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/*"
